import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const source = fileURLToPath(new URL("../../console/dist/", import.meta.url));
const output = fileURLToPath(new URL("../assets.generated.ts", import.meta.url));
const assets: Record<string, string> = {};

async function collect(directory: string) {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) {
      await collect(path);
    } else if (entry.isFile()) {
      assets[relative(source, path).replaceAll("\\", "/")] = (await readFile(path)).toString(
        "base64",
      );
    }
  }
}

await collect(source);
if (!assets["index.html"]) throw new Error("Console build did not produce index.html");
await writeFile(
  output,
  `// Generated by scripts/generate-assets.ts.\nexport const consoleAssets: Record<string, string> = ${JSON.stringify(assets)};\n`,
);
