/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as ProvidersIndexRouteImport } from './routes/providers/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as SessionsBaseSlugRouteImport } from './routes/sessions/$baseSlug'
import { Route as ProvidersProviderIdRouteImport } from './routes/providers/$providerId'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'
import { Route as SessionsBaseSlugSessionIdRouteImport } from './routes/sessions/$baseSlug/$sessionId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsBaseSlugRoute = SessionsBaseSlugRouteImport.update({
  id: '/sessions/$baseSlug',
  path: '/sessions/$baseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersProviderIdRoute = ProvidersProviderIdRouteImport.update({
  id: '/providers/$providerId',
  path: '/providers/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsBaseSlugSessionIdRoute =
  SessionsBaseSlugSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => SessionsBaseSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/sessions/$baseSlug': typeof SessionsBaseSlugRouteWithChildren
  '/agents/': typeof AgentsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/sessions/$baseSlug/$sessionId': typeof SessionsBaseSlugSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/sessions/$baseSlug': typeof SessionsBaseSlugRouteWithChildren
  '/agents': typeof AgentsIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/sessions/$baseSlug/$sessionId': typeof SessionsBaseSlugSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/sessions/$baseSlug': typeof SessionsBaseSlugRouteWithChildren
  '/agents/': typeof AgentsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/sessions/$baseSlug/$sessionId': typeof SessionsBaseSlugSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logs'
    | '/settings'
    | '/agents/$agentId'
    | '/providers/$providerId'
    | '/sessions/$baseSlug'
    | '/agents/'
    | '/providers/'
    | '/sessions/'
    | '/sessions/$baseSlug/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logs'
    | '/settings'
    | '/agents/$agentId'
    | '/providers/$providerId'
    | '/sessions/$baseSlug'
    | '/agents'
    | '/providers'
    | '/sessions'
    | '/sessions/$baseSlug/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/logs'
    | '/settings'
    | '/agents/$agentId'
    | '/providers/$providerId'
    | '/sessions/$baseSlug'
    | '/agents/'
    | '/providers/'
    | '/sessions/'
    | '/sessions/$baseSlug/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogsRoute: typeof LogsRoute
  SettingsRoute: typeof SettingsRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  ProvidersProviderIdRoute: typeof ProvidersProviderIdRoute
  SessionsBaseSlugRoute: typeof SessionsBaseSlugRouteWithChildren
  AgentsIndexRoute: typeof AgentsIndexRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$baseSlug': {
      id: '/sessions/$baseSlug'
      path: '/sessions/$baseSlug'
      fullPath: '/sessions/$baseSlug'
      preLoaderRoute: typeof SessionsBaseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$providerId': {
      id: '/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof ProvidersProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$baseSlug/$sessionId': {
      id: '/sessions/$baseSlug/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$baseSlug/$sessionId'
      preLoaderRoute: typeof SessionsBaseSlugSessionIdRouteImport
      parentRoute: typeof SessionsBaseSlugRoute
    }
  }
}

interface SessionsBaseSlugRouteChildren {
  SessionsBaseSlugSessionIdRoute: typeof SessionsBaseSlugSessionIdRoute
}

const SessionsBaseSlugRouteChildren: SessionsBaseSlugRouteChildren = {
  SessionsBaseSlugSessionIdRoute: SessionsBaseSlugSessionIdRoute,
}

const SessionsBaseSlugRouteWithChildren =
  SessionsBaseSlugRoute._addFileChildren(SessionsBaseSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogsRoute: LogsRoute,
  SettingsRoute: SettingsRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  ProvidersProviderIdRoute: ProvidersProviderIdRoute,
  SessionsBaseSlugRoute: SessionsBaseSlugRouteWithChildren,
  AgentsIndexRoute: AgentsIndexRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
