/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as ProvidersIndexRouteImport } from './routes/providers/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as ProvidersProviderIdRouteImport } from './routes/providers/$providerId'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersProviderIdRoute = ProvidersProviderIdRouteImport.update({
  id: '/providers/$providerId',
  path: '/providers/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/agents': typeof AgentsIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/agents/$agentId'
    | '/providers/$providerId'
    | '/sessions/$sessionId'
    | '/agents/'
    | '/providers/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/agents/$agentId'
    | '/providers/$providerId'
    | '/sessions/$sessionId'
    | '/agents'
    | '/providers'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/agents/$agentId'
    | '/providers/$providerId'
    | '/sessions/$sessionId'
    | '/agents/'
    | '/providers/'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  ProvidersProviderIdRoute: typeof ProvidersProviderIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$providerId': {
      id: '/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof ProvidersProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  ProvidersProviderIdRoute: ProvidersProviderIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
